# Generated by Django 3.2 on 2022-11-19 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productprice_price__decimal_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stripe_product_id',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='stripe_price_id',
        ),
        migrations.CreateModel(
            name='ProductCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_cart', to='products.productprice')),
            ],
        ),
    ]
