# Generated by Django 3.2 on 2022-11-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_product_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
