# Generated by Django 3.2 on 2022-11-20 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcart',
            name='status',
        ),
        migrations.AddField(
            model_name='productorder',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_status', to='products.orderstatus'),
        ),
    ]
