# Generated by Django 3.2 on 2022-11-20 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productorder_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentproductorder',
            name='product_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_product', to='products.productorder'),
        ),
    ]
